// <auto-generated />
using System;
using LunchRoulette.DatabaseLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LunchRoulette.DatabaseLayer.Migrations
{
    [DbContext(typeof(LunchRouletteContext))]
    [Migration("20180727141009_AddedRating")]
    partial class AddedRating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LunchRoulette.DatabaseLayer.Entities.Cuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cuisines");
                });

            modelBuilder.Entity("LunchRoulette.DatabaseLayer.Entities.LunchSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CuisineId");

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("CuisineId");

                    b.ToTable("LunchSpots");
                });

            modelBuilder.Entity("LunchRoulette.DatabaseLayer.Entities.LunchSpot", b =>
                {
                    b.HasOne("LunchRoulette.DatabaseLayer.Entities.Cuisine", "Cuisine")
                        .WithMany()
                        .HasForeignKey("CuisineId");
                });
#pragma warning restore 612, 618
        }
    }
}
